### ISSUE TITLE
 厂商推送服务越来越多。。。

### ISSUE THREAD

**Issue by json988** [jiang111/AndroidPush#1]
有没有办法使用热更新或者hook自己的办法 动态的在运行的时候再加入这些第三方包 不然好臃肿 方法数也会膨胀

**Comment by jiang111** [comment]
一般通过hook自己的方法然后做操作基本都是用于热修复,肯定不合适。热更新可以倒是可以，但是太麻烦了。你要想简洁一点，我觉得最好的方法就是打包不同的推送版本到不同的应用市场,来区分小米,华为,魅族

**Comment by wangyuan0217** [comment]
楼上说的分别打 小米/魅族/华为/其它 的包分别上传市场   是有点麻烦，    如果同时集成的话  那后台需要怎么配合呢？

**Comment by jiang111** [comment]
通过RomUtils.rom() 获取到当前rom平台，然后告诉服务器，让服务器根据不同的集成平台来做相关的操作

**Comment by wangyuan0217** [comment]
那当前用户的rom平台 是不是就要和uid 一块绑定到数据库中了    或是有没有其他方案

**Comment by jiang111** [comment]
是的啊，然后让后端通过平台的类型来推送

**Comment by wangyuan0217** [comment]
嗯  多谢
