### ISSUE TITLE
厂商的SDK更新后，这个集成如何同步更新？

### ISSUE THREAD

**Issue by Suninus** [jiang111/AndroidPush#3]

**Comment by jiang111** [comment]
即使sdk更新，用法基本不怎么更新，所以只需要把相关的sdk替换一下就行了，如果出现用法上有比较大的变更，可能就要考虑自己改代码，或者可以在提issue 我来更新

**Comment by Suninus** [comment]
厂商的SDK你放哪儿了？

**Comment by jiang111** [comment]
push模块的gradle里有极光，lib里有小米和华为，最外层的aar里面是魅族

**Comment by Suninus** [comment]
按你这么说，其实我可以自由定制了，比如去掉华为与梅竹，添加个推或信鸽了？

**Comment by jiang111** [comment]
可以啊，用厂商的推送是为了适配厂商的手机， 这样推送到达率会高一点，你加个推什么的没什么意义了
